#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="20"
gaps["bottom"]="4"
gaps["left"]="4"
gaps["right"]="4"
gaps["inner"]="4"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo $(which yabai) --load-sa"

# ===== Tiling setting =========================

yabai -m config layout                      bsp

yabai -m config top_padding                 0
yabai -m config bottom_padding              4
yabai -m config left_padding                4
yabai -m config right_padding               4
yabai -m config window_gap                  4

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config window_topmost              off
yabai -m config window_opacity              on
yabai -m config window_shadow               float

yabai -m config window_border               on
yabai -m config window_border_width         2
yabai -m config active_window_border_color  "0xE0808080"
yabai -m config normal_window_border_color  "0x00010101"
yabai -m config insert_feedback_color       "0xE02d74da"

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.9
yabai -m config window_opacity_duration     0.5
yabai -m config split_ratio                 0.50


yabai -m config window_animation_easing     easeInOutQuint
yabai -m config  window_animation_duration  0.5

yabai -m config auto_balance                off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize
yabai -m config external_bar                main:35:0
yabai -m config external_bar                main:0:1

## ===== Rules ==================================
yabai -m rule --add app="^Arc$" space=1
yabai -m rule --add app="^Safari$" space=1


yabai -m rule --add app="^Ghostty$" space=2
yabai -m rule --add app="^Warp$" space=2



## ===== Signals ================================
#
yabai -m signal --add app='^Ghostty$' event=window_created action='yabai -m space --layout bsp'
yabai -m signal --add app='^Ghostty$' event=window_destroyed action='yabai -m space --layout bsp'
#
yabai -m signal --add event=application_front_switched action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=display_changed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=space_changed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_created action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_destroyed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_focused action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_title_changed action="${ubersicht_spaces_refresh_command}"

~/.config/yabai/scripts/set_padding.sh
yabai -m signal --add event=window_created action="~/.config/yabai/scripts/set_padding.sh"
yabai -m signal --add event=window_destroyed action="~/.config/yabai/scripts/set_padding.sh"
yabai -m signal --add event=window_moved action="~/.config/yabai/scripts/set_padding.sh"
yabai -m signal --add event=window_minimized action="~/.config/yabai/scripts/set_padding.sh"
yabai -m signal --add event=window_deminimized action="~/.config/yabai/scripts/set_padding.sh"
yabai -m signal --add event=space_changed action="~/.config/yabai/scripts/set_padding.sh"
yabai -m signal --add event=display_added action="~/.config/yabai/scripts/set_padding.sh"



yabai -m signal --add event=window_moved action="~/.config/yabai/scripts/terminate_blank_spaces.sh"
yabai -m signal --add event=window_destroyed action="~/.config/yabai/scripts/terminate_blank_spaces.sh"

set +x
printf "yabai: configuration loaded...\\n"
